chain_main:
  actions:
    - type: send
      text: |
        🔗 Тестирование цепочек действий
        
        Проверьте работу разных вариантов chain:
        — Проверка цепочки (7 действий с chain_drop)
        — Вложенные сценарии (разветвление на 2 цепочки)
      inline:
        - ["Проверить цепочку"]
        - ["Вложенные сценарии", "Дроп вложенных сценариев"]
        - [{"Назад": "start_menu"}]

check_chain:
  actions:
    - type: send
      text: "Действие 1: всегда выполняется"
      callback_edit: false
    - type: send
      callback_edit: false
      chain: true
    - type: send
      text: "Действие 3: chain: failed (только если 2 завершилось с ошибкой)"
      callback_edit: false
      chain: failed
    - type: send
      text: "Действие 4: chain: completed (только если 3 завершилось успешно)"
      callback_edit: false
      chain: completed
    - type: send
      callback_edit: false
      chain: completed
      chain_drop: failed
    - type: send
      text: "Действие 6: НЕ ДОЛЖНО ВЫПОЛНИТЬСЯ (после падения 5 с chain_drop)"
      callback_edit: false
      chain: true
    - type: send
      text: "Действие 7: ТОЖЕ НЕ ДОЛЖНО ВЫПОЛНИТЬСЯ (после падения 5 с chain_drop)"
      callback_edit: false
      chain: true

# =============================================================================
# ТЕСТ ВЛОЖЕННЫХ СЦЕНАРИЕВ С РАЗВЕТВЛЕНИЕМ
# =============================================================================

nested_chains:
  actions:
    - type: send
      text: |
        🔗 Тест: Вложенные сценарии
        
        Начинаем основную цепочку...
      inline:
        - [{"Назад": "chain_main"}]
      callback_edit: false
      chain: true
    - type: scenario
      value: ["test_chain.branch_a", "test_chain.branch_b"]
    - type: send
      text: |
        ✅ Основная цепочка завершена
        
        Если вы видите это сообщение, значит обе ветки (A и B) выполнились успешно.
      inline:
        - [{"Назад": "chain_main"}]
      callback_edit: false
      chain: completed

# Ветка A - успешная цепочка
branch_a:
  actions:
    - type: send
      text: "🌿 Ветка A: Действие 1"
      callback_edit: false
      chain: true
    - type: send
      text: "🌿 Ветка A: Действие 2"
      callback_edit: false
      chain: true
    - type: send
      text: "🌿 Ветка A: Действие 3 (завершение)"
      callback_edit: false
      chain: true

# Ветка B - цепочка с ошибкой
branch_b:
  actions:
    - type: send
      text: "🌿 Ветка B: Действие 1"
      callback_edit: false
      chain: true
    - type: send
      text: "🌿 Ветка B: Действие 2 (с ошибкой)"
      callback_edit: false
      chain: failed
    - type: send
      text: "🌿 Ветка B: Действие 3 (НЕ ДОЛЖНО ВЫПОЛНИТЬСЯ)"
      callback_edit: false
      chain: completed

# Тест разветвления с разными условиями
drop_nested_chains:
  actions:
    - type: send
      text: |
        🔗 Тест: Вложенные сценарии
        
        Начинаем основную цепочку, которая должна прерваться на 2 действии...
      inline:
        - [{"Назад": "chain_main"}]
      callback_edit: false
      chain: true
    - type: send
      callback_edit: false
      chain: true
      chain_drop: failed
    - type: scenario
      value: ["test_chain.branch_a", "test_chain.branch_b"]
      chain: any
    - type: send
      text: |
        ✅ Разветвление завершено
        
        Ветка A выполнилась успешно, Ветка B завершилась с ошибкой.
      inline:
        - [{"Назад": "chain_main"}]
      callback_edit: false
      chain: true