speech_test_main:
  actions:
    - type: send
      text: |
        📋 <b>Доступные команды:</b>
        
        • <code>/speech</code> текст — быстрый синтез речи
        • <code>🎤 Тест синтеза речи</code> — выбор голоса через меню
        
        <b>Поддерживаемые голоса:</b>
        👨 Борис, 👩 Наталья, 👨 Тарас, 👩 Марфа, 👨 Сергей, 🇺🇸 Kira
        
        <i>Выберите действие ниже:</i>
      inline:
        - [{"🎤 Выбрать голос": "test_speech.speech_test_voice_selection"}]
        - [{"🔙 Меню": "start_menu"}]
      callback_edit: false

# Синтез речи по команде /speech
speech_test_reply:
  actions:
    - type: send
      text: "🎤 Обрабатываем команду синтеза речи..."
      text_to_speech: "{reply_message_text}"
      placeholder: true
      callback_edit: false
      chain: true
    - type: scenario
      value: "speech_test_text_extraction"
    - type: scenario
      value: "speech_test_result"

# Сценарий для извлечения текста после команды
speech_test_with_text:
  actions:
    - type: send
      text: "🎤 Обрабатываем команду синтеза речи..."
      text_to_speech: "{event_text|regex:(?<=/speech\\s).+}"
      placeholder: true
      callback_edit: false
    - type: send
      text: | 
        📝 Текст для синтеза: <code>{text_to_speech}</code>
        Исходный текст: <code>{event_text}</code>
        Проверка регулярного выражения: <code>{event_text|regex:(?<=/speech\\s).+}</code>
      callback_edit: false
      chain: true
    - type: scenario
      value: "speech_test_text_extraction"
    - type: scenario
      value: "speech_test_result"

speech_test_text_extraction:
  actions:
    - type: validator
      rules:
        text_to_speech:
          - rule: not_empty
          - rule: length_min
            value: 1
      placeholder: true
      chain: true
    - type: send
      text: |
        ❌ Не удалось извлечь текст для синтеза речи
      chain: failed
      chain_drop: completed
    - type: send
      text: "📝 Текст для синтеза: {text_to_speech}"
      placeholder: true
      callback_edit: false
      chain: true
    - type: to_speech
      chain: true

speech_test_result:
  actions:
    - type: send
      text: |
        ❌ Не удалось синтезировать речь
        Исходный текст: <code>{event_text}</code>
      chain: failed
      chain_drop: completed
    - type: send
      text: "✅ Аудиофайл готов!"
      attachment: "{file_path}"
      inline:
        - [{"🎤 Тест синтеза речи": "test_speech.speech_test_voice_selection"}, {"🔙 Меню": "start_menu"}]
      placeholder: true
      callback_edit: false
      chain: true

# Сценарий с выбором голоса
speech_test_voice_selection:
  actions:
    - type: send
      text: "🎤 Выберите голос для синтеза речи:"
      inline:
        - [{"👨 Борис": "test_speech.speech_boris"}, {"👩 Наталья": "test_speech.speech_natalia"}]
        - [{"👨 Тарас": "test_speech.speech_taras"}, {"👩 Марфа": "test_speech.speech_marfa"}]
        - [{"👨 Сергей": "test_speech.speech_sergey"}, {"🇺🇸 Kira": "test_speech.speech_kira"}]
        - [{"🔙 Назад": "test_speech"}]
      callback_edit: false

# Сценарии для разных голосов
speech_boris:
  actions:
    - type: send
      text: "🎤 Синтез речи голосом Бориса..."
      callback_edit: false
    - type: to_speech
      text_to_speech: "Привет! Меня зовут Борис. Это демонстрация синтеза речи."
      voice: "Bys_24000"
      format: "opus"
      chain: completed
    - type: scenario
      value: "speech_test_result"

speech_natalia:
  actions:
    - type: send
      text: "🎤 Синтез речи голосом Натальи..."
      callback_edit: false
    - type: to_speech
      text_to_speech: "Здравствуйте! Я Наталья. Это демонстрация синтеза речи."
      voice: "Nec_24000"
      format: "opus"
      chain: completed
    - type: scenario
      value: "speech_test_result"

speech_taras:
  actions:
    - type: send
      text: "🎤 Синтез речи голосом Тараса..."
      callback_edit: false
    - type: to_speech
      text_to_speech: "Приветствую! Я Тарас. Это демонстрация синтеза речи."
      voice: "Tur_24000"
      format: "opus"
      chain: completed
    - type: scenario
      value: "speech_test_result"

speech_marfa:
  actions:
    - type: send
      text: "🎤 Синтез речи голосом Марфы..."
      callback_edit: false
    - type: to_speech
      text_to_speech: "Добрый день! Меня зовут Марфа. Это демонстрация синтеза речи."
      voice: "May_24000"
      format: "opus"
      chain: completed
    - type: scenario
      value: "speech_test_result"

speech_sergey:
  actions:
    - type: send
      text: "🎤 Синтез речи голосом Сергея..."
      callback_edit: false
    - type: to_speech
      text_to_speech: "Здравствуйте! Я Сергей. Это демонстрация синтеза речи."
      voice: "Pon_24000"
      format: "opus"
      chain: completed
    - type: scenario
      value: "speech_test_result"

speech_kira:
  actions:
    - type: send
      text: "🎤 Синтез речи голосом Kira (английский)..."
      callback_edit: false
    - type: to_speech
      text_to_speech: "Hello! I'm Kira. This is a demonstration of high-quality English voice synthesis."
      voice: "Kin_24000"
      format: "opus"
      chain: completed
    - type: scenario
      value: "speech_test_result"