# Тестовые сценарии для валидатора
validator_main:
  actions:
    - type: user
      user_state: "validator_test"
      expire: 60s
    - type: send
      text: |
        ✅ <b>Тест валидации данных</b>
        
        Пожалуйста, введите сообщение для проверки всех правил валидации.
        После отправки сообщения будут выполнены пять разных проверок.
      inline:
        - [{"🔍 Подписка (1 чат)": "validator_is_member_single"}, {"🔍 Подписка (неск.)": "validator_is_member_multi"}]
        - [{"🔙 Меню": "start_menu"}]

validator_check:
  actions:
    - type: user
      user_state: ""
    - type: request
      request_name: "validator_test"
      chain: true
    - type: validator
      rules:
        request_text:
          - rule: "length_min"
            value: 5
      chain: true
    - type: send
      text: "✅ Проверка длины (min 5) пройдена!"
      chain: completed
    - type: validator
      rules:
        request_text:
          - rule: "starts_with"
            value: "test"
      chain: true
    - type: send
      text: "✅ Проверка на начало строки ('test') пройдена!"
      chain: completed
    - type: validator
      rules:
        request_text:
          - rule: "regex"
            value: "^[A-Za-z0-9\\s]+$"
      chain: true
    - type: send
      text: "✅ Проверка на латиницу и цифры (regex) пройдена!"
      chain: completed
    - type: validator
      rules:
        request_text:
          - rule: "length_max"
            value: 100
      chain: true
    - type: send
      text: "✅ Проверка длины (max 100) пройдена!"
      chain: completed
    - type: validator
      rules:
        request_text:
          - rule: "contains"
            value: "валид"
      chain: true
    - type: send
      text: "✅ Проверка на наличие подстроки 'валид' пройдена!"
      chain: completed 

# Проверка членства в одном чате/канале
validator_is_member_single:
  actions:
    - type: validator
      rules:
        user_id:
          - rule: "is_member"
            chat: -1002749258418
            on_error: "drop"
      chain: true
    - type: scenario
      value: ["validator_result_completed", "validator_result_failed", "validator_result_drop"]

# Проверка членства в нескольких чатах/каналах
validator_is_member_multi:
  actions:
    - type: validator
      rules:
        user_id:
          - rule: "is_member"
            chat:
              - -1002749258418   # TODO: замените на реальный chat_id или "@channel_username"
              - -1002222222222   # TODO: замените на реальный chat_id или "@channel_username"
            mode: "any"
            on_error: "pass"
      chain: true
    - type: scenario
      value: ["validator_result_completed", "validator_result_failed", "validator_result_drop"]

validator_result_failed:
  actions:
    - type: send
      text: "❌ Пользователь не состоит в указанном чате/канале"
      callback_edit: false
      chain: failed
      chain_drop: completed

validator_result_drop:
  actions:
    - type: send
      text: "⚠️ Не удалось проверить членство в чате/канале"
      callback_edit: false
      chain: drop
      chain_drop: completed

validator_result_completed:
  actions:
    - type: send
      text: "✅ Пользователь состоит во всех указанных чатах/каналах"
      callback_edit: false
      chain: completed