# Основное меню тестирования STT
test_stt_main:
  actions:
    - type: user
      user_state: ""
    - type: send
      text: |
        📋 <b>Выберите тип тестирования:</b>
        
        🔄 <b>Синхронный метод</b> - быстрая обработка небольших текстов
        ⏳ <b>Асинхронный метод</b> - обработка длинных текстов  
        🎯 <b>Общий тест</b> - переключение статуса и ожидание аудиофайла
        
        <i>Выберите действие ниже:</i>
      inline:
        - [{"🔄 Синхронный STT": "sync_stt_test"}, {"⏳ Асинхронный STT": "async_stt_test"}]
        - [{"🎯 Общий тест": "general_stt_test"}]
        - [{"🔙 Меню": "start_menu"}]
      callback_edit: false

# Синхронный тест STT
sync_stt_test:
  actions:
    - type: send
      text: "🔄 Тест синхронного STT"
      callback_edit: false
    - type: send
      text: |
        📁 Используется файл: <code>speech/examples/Александра.mp3</code>
        ⚙️ Метод: Синхронный API SaluteSpeech
        
        Обрабатываем...
      attachment: 
        - "speech/examples/Александра.mp3"
      callback_edit: false
      chain: true
    - type: from_speech
      audio_file: "speech/examples/Александра.mp3"
      voice: "Ost_24000"
      chain: completed
    - type: scenario
      value: "stt_result"

# Асинхронный тест STT
async_stt_test:
  actions:
    - type: send
      text: "⏳ Тест асинхронного STT"
      callback_edit: false
    - type: send
      text: |
        📁 Используется файл: <code>speech/examples/Борис.mp3</code>
        ⚙️ Метод: Асинхронный API SaluteSpeech
        
        Обрабатываем...
      attachment: 
        - "speech/examples/Борис.mp3"
      callback_edit: false
      chain: true
    - type: from_speech
      audio_file: "speech/examples/Борис.mp3"
      voice: "Bys_24000"
      chain: completed
    - type: scenario
      value: "stt_result"

# Общий тест STT с переключением статуса
general_stt_test:
  actions:
    - type: user
      user_state: "waiting_audio_upload"
      chain: true
    - type: send
      text: |
        📤 <b>Загрузите аудиофайл для тестирования STT</b>
        
        📋 Статус: Ожидание аудиофайла
        🎵 Действие: Загрузите любой аудиофайл (.mp3, .ogg, .wav)
        
        После загрузки файл будет обработан через STT
      inline:
        - [{"🔙 Назад": "test_stt_main"}]
      callback_edit: false
      chain: completed

# Обработка загруженного аудиофайла
handle_audio_upload:
  actions:
    - type: request
      request_name: "stt_test"
    - type: scenario
      value: stt_validation
    - type: from_speech
      chain: completed
    - type: scenario
      value: "stt_result"

# Результат STT
stt_result:
  actions:
    - type: send
      text: |
        ❌ Не удалось синтезировать речь
      chain: failed
      chain_drop: completed
    - type: send
      text: "✅ STT завершен успешно!"
      callback_edit: false
      chain: true
    - type: send
      text: "{speech_to_text}"
      inline:
        - [{"🔙 Назад": "test_stt_main"}]
      placeholder: true
      callback_edit: false
      chain: true

stt_validation:
  actions:
    - type: validator
      rules:
        attachments:
          - rule: "not_empty"
      chain: true
    - type: send
      text: |
        ❌ Отсутствует аудиофайл
      message_reply: true
      chain: failed
      chain_drop: completed
    - type: send
      text: |
        🎵 Файл получен!

        Обрабатываем через STT...
      callback_edit: false
      chain: true

stt_from_command:
  actions:
    - type: validator
      attachments: "{reply_attachments}"
      placeholder: true
      chain: true
    - type: scenario
      value: stt_validation
    - type: from_speech
      chain: completed
    - type: scenario
      value: "stt_result"