# Тестовые сценарии для новых типов триггеров (starts_with и regex)
# Демонстрирует работу с приоритетами: exact → state → starts_with → regex → contains

starts_with_start:
  actions:
    - type: "send"
      text: |
        🎯 **starts_with триггер сработал!**

        Команда `/start` (или начинающаяся с неё) была обработана через `starts_with`.

        Примеры:
        • `/start` ✅
        • `/start param` ✅
        • `/start user123` ✅
        • `можно проверить /start` ❌

regex_start_with_three_params:
  actions:
    - type: "send"
      text: |
        🔍 **regex триггер сработал!**

        Команда `/start` с тремя обязательными параметрами была обработана через `regex`.

        Паттерн: `^/start\\s+\\w+\\s+\\w+\\s+\\w+$`

        Примеры:
        • `/start user admin role` ✅
        • `/start john moderator vip` ✅
        • `/start user admin` ❌ (два параметра)
        • `/start user` ❌ (один параметр)
        • `/start user admin role extra` ❌ (четыре параметра)

regex_start_with_two_params:
  actions:
    - type: "send"
      text: |
        🔍 **regex триггер сработал!**

        Команда `/start` с двумя обязательными параметрами была обработана через `regex`.

        Паттерн: `^/start\\s+\\w+\\s+\\w+$`

        Примеры:
        • `/start user admin` ✅
        • `/start john moderator` ✅
        • `/start` ❌ (нет параметров)
        • `/start user` ❌ (один параметр)
        • `/start user admin extra` ❌ (три параметра)