roles_main:
  actions:
    - type: send
      text: |
        🔐 📋 Тестирование ролевой модели
        
        Проверьте работу ролей и доступов:
        ————————————————
        • Роли — тест доступа к ролям
        • Доступы — тест доступа к разрешениям
        • Вместе — тест комбинированного доступа
      inline:
        - ["Роли", "Доступы", "Вместе"]
        - [{"Назад": "start_menu"}]

roles:
  actions:
    - type: send
      text: |
        👥 🔑 Тест: Роли
        
        ✅ Первое сообщение — отправляется (есть доступ к ролям)
        ❌ Второе сообщение — не отправляется (нет доступа к ролям)
      inline:
        - [{"Назад": "roles_main"}]
      callback_edit: false
      chain: true
      required_role: ["admin", "moderator"]
    - type: scenario
      value: "test_roles.no_access"
    - type: send
      text: |
        👥 🔑 Тест: Роли (продолжение)
        
        Это второе сообщение в цепочке ролей.
        Если вы его видите, значит у вас есть права admin или moderator.
      inline:
        - [{"Назад": "roles_main"}]
      callback_edit: false
      chain: any
      required_role: ["no_role"]
    - type: scenario
      value: "test_roles.no_access"

permissions:
  actions:
    - type: send
      text: |
        🔑 🔐 Тест: Доступы
        
        ✅ Первое сообщение — отправляется (есть доступ к разрешениям)
        ❌ Второе сообщение — не отправляется (нет доступа к разрешениям)
      inline:
        - [{"Назад": "roles_main"}]
      callback_edit: false
      chain: any
      required_permission: ["test_permissions"]
    - type: scenario
      value: "test_roles.no_access"
    - type: send
      text: |
        🔑 🔐 Тест: Доступы (продолжение)
        
        Это второе сообщение в цепочке разрешений.
        Если вы его видите, значит у вас есть разрешение test_permissions.
      inline:
        - [{"Назад": "roles_main"}]
      callback_edit: false
      chain: any
      required_permission: ["no_permissions"]
    - type: scenario
      value: "test_roles.no_access"

roles_permissions:
  actions:
    - type: send
      text: |
        🔐 🔗 Тест: Роли + Доступы
        
        ✅ Первое сообщение — отправляется (есть комбинированный доступ)
        ❌ Второе сообщение — не отправляется (нет комбинированного доступа)
      inline:
        - [{"Назад": "roles_main"}]
      callback_edit: false
      chain: any
      required_role: ["admin"]
      required_permission: ["test_permissions"]
    - type: scenario
      value: "test_roles.no_access"
    - type: send
      text: |
        🔐 🔗 Тест: Роли + Доступы (продолжение)
        
        Это второе сообщение в цепочке комбинированного доступа.
        Если вы его видите, значит у вас есть роль admin И разрешение test_permissions.
      inline:
        - [{"Назад": "roles_main"}]
      callback_edit: false
      chain: any
      required_role: ["admin"]
      required_permission: ["no_permissions"]
    - type: scenario
      value: "test_roles.no_access"

no_access:
  actions:
    - type: send
      text: |
        ❌ 🚫 Доступ запрещен

        У вас нет прав для просмотра информации.
      inline:
        - [{"Назад": "roles_main"}]
      callback_edit: false
      chain: failed