# Тестовые сценарии для сервиса промокодов
promocode_main:
  actions:
    - type: "user"
      user_state: ""
    - type: send
      text: |
        🎫 <b>Тестирование сервиса промокодов</b>
        
        Выберите действие для тестирования:
        ————————————————
        • 🎲 Генерация случайного промокода
        • 🔒 Генерация постоянного промокода
        • ✏️ Модификация промокода
        • 🔍 Проверка промокода
        • 📋 Список промокодов пользователя
        • 🌐 Все активные промокоды
        
        <i>Сервис автоматически создаст действия в базе данных для обработки промокодов.</i>
      inline:
        - [{"🎲 Случайный": "promocode_random"}, {"🔒 Постоянный": "promocode_deterministic"}]
        - [{"✏️ Модификация": "promocode_modify"}, {"🔍 Проверка": "promocode_check_state"}]
        - [{"📋 Мои промокоды": "promocode_user_list"}, {"🌐 Все активные": "promocode_all_active"}]
        - [{"🔙 Меню": "start_menu"}]

# =============================================================================
# ГЕНЕРАЦИЯ СЛУЧАЙНОГО ПРОМОКОДА
# =============================================================================

promocode_random:
  actions:
    - type: create_promo
      promo_name: "test_random"
      length: 8
      use_digits: true
      use_letters: true
      use_random: true
    - type: send
      text: |
        🎲 <b>Генерация случайного промокода</b>
        
        Создаю случайный промокод с параметрами:
        • Длина: <code>{promo_code|length}</code> символов
        • Цифры: <code>{use_digits|fallback:None}</code>
        • Буквы: <code>{use_letters|fallback:None}</code>
        • Случайный: <code>{use_random|fallback:None}</code>
        
        <i>Промокод будет доступен всем пользователям.</i>

        Ваш промокод: <code>{promo_code}</code> действует до <code>{expired_at|format:date}</code>
      inline:
        - [{"🔙 Назад": "promocode_main"}]
      callback_edit: false
      chain: true

# =============================================================================
# ГЕНЕРАЦИЯ ПОСТОЯННОГО ПРОМОКОДА
# =============================================================================

promocode_deterministic:
  actions:
    - type: create_promo
      promo_name: "test_deterministic"
      target_user_id: "Any"  # Доступен всем
      length: 10
      use_digits: true
      use_letters: false
      use_random: false
    - type: send
      text: |
        🔒 <b>Генерация постоянного промокода</b>
        
        Создаю постоянный промокод с параметрами:
        • Длина: <code>{promo_code|length}</code> символов
        • Цифры: <code>{use_digits|fallback:None}</code>
        • Буквы: <code>{use_letters|fallback:None}</code>
        • Случайный: <code>{use_random|fallback:None}</code>
        • Соль: <code>{salt|fallback:None}</code>
        
        <i>При одинаковых параметрах всегда будет генерироваться один и тот же код.</i>

        Ваш промокод: <code>{promo_code}</code> действует до <code>{expired_at|format:date}</code>
      inline:
        - [{"🔙 Назад": "promocode_main"}]
      callback_edit: false
      chain: true

# =============================================================================
# МОДИФИКАЦИЯ ПРОМОКОДА
# =============================================================================

promocode_modify:
  actions:
    - type: modify_promo
      promo_id: 1  # ID промокода для модификации
      promo_name: "new_name"
      target_user_id: "Any"  # Сделать доступным всем
    - type: send
      text: |
        ✏️ <b>Модификация промокода</b>
        
        Модифицирую промокод с параметрами:
        • ID: <code>{promo_id}</code>
        • Новое название: <code>{promo_name}</code>
        • Доступ: для всех пользователей
        
        <i>Промокод успешно обновлен в базе данных.</i>

        Результат модификации: <code>{promo_code}</code> действует до <code>{expired_at|format:date}</code>
      inline:
        - [{"🔙 Назад": "promocode_main"}]
      callback_edit: false
      chain: true

# =============================================================================
# ПРОВЕРКА ПРОМОКОДА
# =============================================================================

promocode_check_state:
  actions:
    - type: "user"
      user_state: "promocode_check"
      expire: 120s
    - type: send
      text: |
        Введите промокод для проверки
      inline:
        - [{"🔙 Назад": "promocode_main"}]
      callback_edit: false
      chain: true

promocode_check:
  actions:
    - type: validator
      promo_code: "{event_text|regex:^[A-Za-z0-9]+$}"
      placeholder: true
    - type: check_promo
      chain: true
    - type: send
      text: |
        🔍 <b>Проверка промокода</b>
        
        Проверяю промокод с параметрами:
        • Код: <code>{promo_code}</code>
        
        <i>Система проверила существование, срок действия и доступность.</i>

        Результат проверки: <code>{promo_available}</code> доступен до <code>{promo_data.expired_at|format:date}</code>
      inline:
        - [{"🔙 Назад": "promocode_main"}]
      callback_edit: false
      chain: true
    - type: user
      user_state: ""
      chain: true

# =============================================================================
# СПИСОК ПРОМОКОДОВ ПОЛЬЗОВАТЕЛЯ
# =============================================================================

promocode_user_list:
  actions:
    - type: promo_management
      operation: "list"
      user_filter: "{user_id}"
    - type: send
      text: |
        📋 <b>Ваши промокоды</b>
        
        {response_text}
        
        <i>Для просмотра деталей промокода введите его ID в следующем сообщении.</i>
      inline:
        - [{"🔙 Назад": "promocode_main"}]
      callback_edit: false
      chain: true
    - type: user
      user_state: "promocode_details"
      chain: true

# =============================================================================
# СПИСОК ВСЕХ АКТИВНЫХ ПРОМОКОДОВ
# =============================================================================

promocode_all_active:
  actions:
    - type: promo_management
      operation: "list"
      status: "active"  # Все активные промокоды
    - type: send
      text: |
        🌐 <b>Все активные промокоды</b>
        
        {response_text}
        
        <i>Для просмотра деталей промокода введите его ID в следующем сообщении.</i>
      inline:
        - [{"🔙 Назад": "promocode_main"}]
      callback_edit: false
      chain: true
    - type: user
      user_state: "promocode_details"
      chain: true

# =============================================================================
# ПОКАЗ ДЕТАЛЕЙ ПРОМОКОДА ПО ID
# =============================================================================

promocode_details:
  actions:
    - type: validator
      promo_id: "{event_text|regex:^[0-9]+$}"
      placeholder: true
    - type: promo_management
      operation: "details"
      promo_id: "{promo_id}"
      chain: true
    - type: send
      text: |
        🔍 <b>Детали промокода #{promo_id}</b>
        
        {response_text}
        
        <i>Промокод успешно загружен из базы данных.</i>
      inline:
        - [{"🔙 Назад": "promocode_main"}]
      callback_edit: false
      chain: true
    - type: user
      user_state: ""
      chain: true

# =============================================================================
# ВСПОМОГАТЕЛЬНЫЕ СЦЕНАРИИ
# =============================================================================

# Сценарий для возврата в главное меню промокодов (с удалением)
promocode_main_clean:
  actions:
    - type: remove
    - type: scenario
      value: "promocode_main"