# Сценарии для тестирования запросов с состояниями пользователей

# Главное меню тестирования запросов
request_main:
  actions:
    - type: "user"
      user_state: ""
    - type: "send"
      text: |
        🧪 <b>Тестирование запросов</b>
        
        Выберите тип запроса для тестирования:
        ————————————————
        • Обратная связь — отправить пожелания
        • Сообщить об ошибке — сообщить о проблеме
      inline:
        - ["📝 Обратная связь"]
        - [{"🔙 Назад": "start_menu"}]

# Запрос обратной связи
request_feedback_state:
  actions:
    - type: "user"
      user_state: "feedback"
      expire: 10s
    - type: "send"
      text: |
        📝 <b>Обратная связь</b>
        
        Пожалуйста, опишите ваши пожелания, предложения или замечания.
        Мы внимательно изучим ваше сообщение и учтем его в дальнейшей работе.
        
        <i>Просто напишите ваше сообщение в следующем сообщении.</i>
      inline:
        - [{"🔙 Назад": "request_main"}]
      chain: completed

# Обработка обратной связи (сценарий для состояния feedback)
request_feedback:
  actions:
    - type: "user"
      user_state: ""
    - type: "request"
      request_name: "feedback"
      request_info: "Фидбек от пользователя {user_id} (@{username}) в чате {chat_id}. Запрос: '{request_name}'. Текст: {event_text}"
    - type: "send"
      text: |
        ✅ <b>Спасибо за обратную связь!</b>
        
        Ваше сообщение успешно получено и будет рассмотрено нашей командой.
        Мы обязательно учтем ваши пожелания в дальнейшей работе.
        
        🔙 <a href="command.start">Вернуться в главное меню</a>
      inline:
        - [{"🔙 Назад": "request_main"}]
      chain: completed