messages_main:
  actions:
    - type: send
      text: |
        💬 📋 Тестирование сервиса сообщений
        
        Проверьте разные варианты отправки сообщений:
        ————————————————
        • Без вложений
        • 1 вложение
        • 2-3 вложения
        • Reply клавиатура
        • Inline и Reply
      inline:
        - ["Без вложений", "1 вложение", "2-3 вложения"]
        - ["Reply клавиатура", "Inline и Reply"]
        - [{"🌐 Документация": "https://core.telegram.org/bots/api"}]
        - [{"Назад": "start_menu"}]

# Сценарий для возвратов из вложений (с удалением)
messages_main_clean:
  actions:
    - type: remove
    - type: scenario
      value: "test_messages.messages_main"

no_attachment:
  actions:
    - type: send
      text: |
        ✏️ 📝 Тест: редактирование сообщения
        
        Это пример редактирования сообщения.
      inline:
        - [{"Назад": "messages_main"}]
      callback_edit: true
    - type: send
      text: |
        ✉️ 📝 Тест: простое сообщение
        
        Это пример простого текстового сообщения (не редактируется).
      inline:
        - [{"Назад": "messages_main"}]
      callback_edit: false
      chain: true

one_attachment:
  actions:
    - type: send
      text: |
        🖼️ 📸 Тест: 1 вложение (фото/видео)
        
        Отправка одного медиа-файла как вложения.
      inline:
        - [{"Назад": "messages_main_clean"}]
      attachment: "logo.png"
      callback_edit: false
    - type: send
      text: |
        🎬 🎭 Тест: 1 вложение (GIF анимация)
        
        Отправка GIF как анимации с воспроизведением.
      inline:
        - [{"Назад": "messages_main_clean"}]
      attachment: "waterfall.gif"
      callback_edit: false
    - type: send
      text: |
        📄 📋 Тест: 1 вложение (документ)
        
        Отправка одного документа как вложения.
      inline:
        - [{"Назад": "messages_main_clean"}]
      attachment: "file.pdf"
      callback_edit: false
      chain: true
    - type: send
      text: |
        🖼️ 🎥 Тест: 1 вложение (фото/видео)
        
        Отправка одного медиа-файла как вложения.
      inline:
        - [{"Назад": "messages_main_clean"}]
      attachment: "city.mp4"
      callback_edit: false
      chain: true
    - type: send
      text: |
        🖼️📄 📋 Тест: медиа-файл как документ
        
        Отправка медиа-файла с явным типом document (без сжатия).
      inline:
        - [{"Назад": "messages_main_clean"}]
      attachment:
        file: "logo.png"
        type: "document"
      callback_edit: false
      chain: true

multi_attachment:
  actions:
    - type: send
      text: |
        🖼️🖼️ 📸 Тест: группа фото/видео
        
        Отправка группы только фото/видео (media_group).
      inline:
        - [{"Назад": "messages_main_clean"}]
      attachment:
        - "logo.png"
        - "city.mp4"
      callback_edit: false
    - type: send
      text: |
        📄📄 📋 Тест: группа документов
        
        Отправка группы только документов.
      inline:
        - [{"Назад": "messages_main_clean"}]
      attachment:
        - "file.pdf"
        - "file.pdf"
      callback_edit: false
      chain: true
    - type: send
      text: |
        🖼️📄 🔀 Тест: смешанная группа
        
        Отправка смешанной группы вложений (фото, видео, анимации и документы). Сервис разобьёт на несколько сообщений по типу.
      inline:
        - [{"Назад": "messages_main_clean"}]
      attachment:
        - "logo.png"
        - "file.pdf"
        - "city.mp4"
        - "waterfall.gif"
        - "file.pdf"
        - "waterfall.gif"
      callback_edit: false
      chain: true

# =============================================================================
# ТЕСТЫ REPLY КЛАВИАТУРЫ
# =============================================================================

inline_and_reply:
  actions:
    - type: send
      text: |
        ⌨️ 📱 Тест: Inline и Reply клавиатура
      inline:
        - ["Кнопка 1", "Кнопка 2", "Кнопка 3"]
        - ["Кнопка 4", "Кнопка 5"]
        - ["Убрать клавиатуру"]
      reply:
        - ["Кнопка 1", "Кнопка 2", "Кнопка 3"]
        - ["Кнопка 4", "Кнопка 5"]
        - ["Убрать клавиатуру"]
      callback_edit: false

reply_keyboard:
  actions:
    - type: send
      text: |
        ⌨️ 📱 Тест: Reply клавиатура
        
        Это сообщение с обычной клавиатурой (ReplyKeyboardMarkup).
        Клавиатура будет отображаться под полем ввода сообщения.
      reply:
        - ["Кнопка 1", "Кнопка 2", "Кнопка 3"]
        - ["Кнопка 4", "Кнопка 5"]
        - ["Убрать клавиатуру"]
      callback_edit: false

remove_keyboard:
  actions:
    - type: send
      text: |
        🗑️ ⌨️ Тест: Убрать клавиатуру
        
        Это сообщение убирает Reply клавиатуру.
        После этого сообщения клавиатура исчезнет.
      reply: []  # Пустая клавиатура = убрать клавиатуру
      callback_edit: false 