# Список команд, которые будут зарегистрированы в Telegram Bot API
commands:
  - command: "start"
    description: "Запустить бота"
    scope: all_private_chats
  - command: "help"
    description: "Справка"
    scope: all_private_chats
  - command: "link"
    description: "Ссылка на группу"
    scope: all_group_chats

# Ролевая модель: управление доступом пользователей к функциям бота
# Каждая роль содержит список permissions (разрешений) и users (ID пользователей)
# В сценариях можно указать required_role (требуемая роль) или required_permission (требуемые разрешения)
# Приоритет: required_permission > required_role. Если указаны оба - проверяются только permissions
roles:
  admin:
    description: "Администратор"
    permissions:
      - "test_roles"
      - "test_permissions"
    users: [1133574222]               # ID (user_id) пользователей
  
  moderator:
    description: "Модератор"
    permissions:
      - "test_roles"
    users: [7650826763, 1133574222]   # ID (user_id) пользователей