text:
  exact:
    # Команды
    "/start": "command.start"
    "/help": "command.help"
    "/speech": "speech_test_reply"
    "/stt": "stt_from_command"
    # Reply клавиатура
    "Убрать клавиатуру": "test_messages.remove_keyboard"
  state:
    "feedback": "test_request.request_feedback"
    "validator_test": "test_validation.validator_check"
    "request_details": "request_check.request_check_details_get"
    "waiting_audio_upload": "handle_audio_upload"
    "promocode_check": "promocode_check"
    "promocode_details": "promocode_details"
  regex:
    "^/start\\s+\\w+\\s+\\w+\\s+\\w+$": "test_trigger.regex_start_with_three_params"
    "^/start\\s+\\w+\\s+\\w+$": "test_trigger.regex_start_with_two_params"
    "^/speech\\s+(.+)$": "speech_test_with_text"
  starts_with:
    "/linkdrop": "group.link.link_drop"
    "/start": "test_trigger.starts_with_start"
  contains: {}
callback:
  exact:
    # Меню
    "Меню": "start"
    "Назад": "start"
    "Тест сообщений": "menu.test_messages"
    "Тест ролей": "menu.test_roles"
    "Тест запросов": "menu.test_requests"
    "Тест цепочки": "menu.test_chain"
    "Тест валидации": "menu.test_validation"
    "Проверка запросов": "menu.test_request_check"
    "Тест плейсхолдеров": "test_placeholder.placeholder_main"
    "Тест синтеза речи": "menu.test_speech"
    "Тест STT": "test_stt_main"
    # Тест сообщений
    "Простой тест": "test_messages.no_attachment"
    "1 вложение": "test_messages.one_attachment"
    "2-3 вложения": "test_messages.multi_attachment"
    "Reply клавиатура": "test_messages.reply_keyboard"
    "Убрать клавиатуру": "test_messages.remove_keyboard"
    "Inline и Reply": "test_messages.inline_and_reply"
    # Тест ролей
    "Роли": "test_roles.roles"
    "Доступы": "test_roles.permissions"
    "Вместе": "test_roles.roles_permissions"
    # Тест запросов
    "Обратная связь": "test_request.request_feedback_state"
    "Сообщить об ошибке": "test_request.request_bug_report_state"
    # Проверка запросов
    "7 дней": "request_check.request_check_last_7_days"
    "С даты": "request_check.request_check_from_date"
    "Все": "request_check.request_check_all"
    "Последние 10": "request_check.request_check_last_10"
    "Детали": "request_check.request_check_details_state"
    # Тест цепочки и сценариев
    "Проверить цепочку": "test_chain.check_chain"
    "Вложенные сценарии": "test_chain.nested_chains"
    "Дроп вложенных сценариев": "test_chain.drop_nested_chains"
  contains: {}