welcome_group_main:
  actions:
    - type: send
      text: |
        👥 Сработал триггер group: Добро пожаловать в основную группу!
        Список: 
        {joined_usernames|tags}

welcome_from_link:
  actions:
    - type: send
      text: |
        🔗 Сработал триггер link: Вы присоединились по специальной ссылке!
        {joined_usernames|tags}

welcome_from_creator:
  actions:
    - type: send
      text: |
        👤 Сработал триггер creator: Вас пригласил особый пользователь!
        {joined_usernames|tags}

welcome_added_by_initiator:
  actions:
    - type: send
      text: |
        ➕ Сработал триггер initiator: Вас добавил определённый человек!
        {joined_usernames|tags}

welcome_default:
  actions:
    - type: send
      text: |
        🤖 Сработал триггер default: Стандартное приветствие для новых участников!
        {joined_usernames|tags}